version: '3.9'

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - flask_db
    networks:
      - backend

  flask_db:
    container_name: flask_db
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - backend

networks:
  backend: