version: '3.9'

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .dev.env
    ports:
      - "4444:4444"
    depends_on:
      - flask_db
    networks:
      - backend

  flask_db:
    container_name: flask_db
    image: postgres:12.0-alpine
    hostname: flask_db
    env_file:
      - .db.env
    expose:
      - 5432
    networks:
      - backend

networks:
  backend: