services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .dev.env
    ports:
      - "4444:4444"
    depends_on:
      flask_db:
        condition: service_healthy
        restart: true
    networks:
      - backend

  flask_db:
    container_name: flask_db
    image: postgres:12.0-alpine
    hostname: flask_db
    env_file:
      - .db.env
    expose:
      - 5432
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'pg_isready -U postgres'"]
      interval: 15s
      timeout: 3s
      retries: 3

networks:
  backend: